### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by alexiarstein** [riggraz/astuto#451]
Good morning. I deployed the docker version, logged in well using admin@example.com / pw password for the first time, then edited my profile to use my actual email account and a different password, and from then on, It did not allow me to login. 

So I stopped the containers, removed them, removed the docker images, and ran docker-compose pull again, 

The problem here is that now admin@example.com / pw password do not work. 

Is the database info being stored somewhere else outside the containers? or is there a way I could edit the fields in the db to edit the account info?

Thank you!

**Comment by alexiarstein** [comment]
Partially fixed by hashing a new password and altering the user straight from the postgres in the container. But I still cannot use a different email than admin@example.com because it is not sending me the email. 

These are my smtp settings in my docker-compose.yml file, can you tell me what's wrong with them please?

```
version: "3.8"
services:
  db:
    image: postgres:14.5
    environment: &db-env
      POSTGRES_USER: mypostgresuser
      POSTGRES_PASSWORD: mypostgrespassword
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    image: riggraz/astuto:latest
    environment:
      <<: *db-env
      BASE_URL: http://roadmap.mydomain.com
      SECRET_KEY_BASE: mysecretkey
      EMAIL_DELIVERY_METHOD: smtp
      EMAIL_SMTP_HOST: smtp.mailgun.org
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: noreply@mydomain.org
      EMAIL_SMTP_PASS: mypassword
      EMAIL_MAIL_FROM: noreply@mydomain.org
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  dbdata:
```
